README.md
Did a find/replace for ">" in the README in the last PR #72 that merged. Shouldn't have done that 🙆It broke the rendering of the logo and badges. This PR fixes it
=> 🐛 Fix result of find/replace in README html

.gitignore, src/common/misc.py, src/common/stage.py, src/etl/extract/extract.py, src/etl/ingest_pipeline.py, src/etl/load/load.py, src/etl/transform/transform.py, tests/test_extract_stage.py, tests/test_ingest_stage.py
branched from extract-testing (PR #77). approve that first, please. will rebase when that merges.
=> ✨ serialize/deserialize extract stage output

src/common/file_retriever.py
=>  🐛 continue past failing s3 profiles

dev-requirements.txt, scripts/test.sh
=> ⬆️ pep8 has been renamed to pycodestyle

requirements.txt
See https://nvd.nist.gov/vuln/detail/CVE-2017-18342
=> ⬆️ Upgrade pyyaml to fix vulnerability

kf_lib_data_ingest/etl/extract/extract.py, kf_lib_data_ingest/etl/transform/guided.py, tests/conftest.py, tests/data/test_study/transform_module.py, tests/test_guided_transform.py
=> ✨ GuidedTransformer - apply user transform funct

kf_lib_data_ingest/common/stage.py, kf_lib_data_ingest/etl/ingest_pipeline.py, kf_lib_data_ingest/etl/transform/transform.py, tests/conftest.py, tests/data/test_study/transform_module.py, tests/test_extract_stage.py, tests/test_ingest_stage.py, tests/test_transform_stage.py
PR combines a couple small things
- Do some common read/write stuff in stage.py (just see code)
- Implement transform stage read/write
=> ✨ More stage read/write

kf_lib_data_ingest/common/datafile_readers.py, kf_lib_data_ingest/etl/extract/extract.py, kf_lib_data_ingest/etl/extract/operations.py, tests/data/test_study/extract_configs/simple_tsv_example2.py, tests/data/test_study/extract_outputs/simple_tsv_example1_output.tsv, tests/data/test_study/extract_outputs/simple_tsv_example2_output.tsv, tests/data/test_study/extract_outputs/unsimple_xlsx_example1_output.tsv, tests/test_extract_operations.py, tests/test_extract_stage.py
put the row index that a value came from into the extract output
=> ✨ preserve row index across extract

docs/source/conf.py, docs/source/index.rst, docs/source/reference/common.rst, docs/source/tutorial/extract.rst, docs/source/tutorial/index.rst, docs/source/tutorial/project_setup.rst, docs/source/tutorial/study_configuration.rst
It was easier to make a PR against your branch to give comments/suggestions. Would be easiest to pull down this branch and run `make html` to see the changes in final form. 
I really like the way [Django does their docs](https://www.django-rest-framework.org/tutorial/quickstart/). They have both a quickstart section that just shows you how to get up and running with a simple API, and with little to no explanation. The main purpose is to show you the end result. Then they also have a more in-depth tutorial where they explain each step towards the end result in detail. I had their docs in mind when writing these suggestions.
Here are the main things to note:
- I tried to make things have more of a natural flow/connect better
- Added a top level tutorial section
- Separated …
=> ♻️ PR Review Suggestions for Extract Docs

doc-requirements.txt
=> 🐛 Fix url for kf sphinx theme req

doc-requirements.txt, docs/source/conf.py, docs/source/developer.rst, docs/source/index.rst, docs/source/install.rst, docs/source/quickstart.rst, docs/source/tutorial/extract.rst, docs/source/tutorial/index.rst, docs/source/tutorial/project_setup.rst, docs/source/tutorial/study_configuration.rst, scripts/build.sh
=> 📝 how to configure a new study

kf_lib_data_ingest/etl/configuration/extract_config.py, kf_lib_data_ingest/etl/extract/extract.py, tests/test_extract_stage.py
read_table to read_csv because pandas has decided (sigh) to deprecate
the former
more help output
json file default loader
=> ♻️ refactor _source_file_to_df

kf_lib_data_ingest/common/misc.py, kf_lib_data_ingest/etl/extract/extract.py, tests/data/test_study/extract_outputs/split_rows_tsv_example1_output.tsv, tests/test_extract_stage.py, tests/test_misc.py
Maybe we should just remove the line though? I didn't realize it before, but this replacement currently gets shadowed by the later call to intsafe_str anyway.
=>  🐛 extract data cleaning (bug #147)

requirements.txt
=> 🐛 Add requests package to requirements

kf_lib_data_ingest/etl/transform/guided.py, kf_lib_data_ingest/etl/transform/transform.py, tests/data/test_boyd_study/dataset_ingest_config.yml, tests/data/test_boyd_study/extract_configs/manifest_180917_rectified_map.py, tests/data/test_boyd_study/extract_configs/s3_files_kf-seq-data-hudsonalpha_haib17SB5136_map.py, tests/data/test_boyd_study/transform_module.py, tests/test_guided_transform.py, tests/test_transform_stage.py
Meant to merge branch `finish-guided-transfrom` into `master` not `small-refactor-and-fixes`
=> ✨ Finish guided transform

scripts/build.sh, scripts/test.sh
Closes #158 
Please review #164 first, will rebase after #164 merges.
=> 👷Run ingest in CI to verify build worked

docs/source/index.rst
=> ✨ Make ingest-pipeline.png clickable

kf_lib_data_ingest/etl/transform/common.py, kf_lib_data_ingest/etl/transform/transform.py, tests/test_null_processing.py
- Add more informative log statements in transform
- Fix bug in null processing where null processing would continue even when no schema was found for the target concept
- Add a couple more null processing tests
=> 🐛 🔊 Fix null processing and better logging

kf_lib_data_ingest/common/file_retriever.py, kf_lib_data_ingest/etl/extract/extract.py, tests/test_file_retriever.py
=>  🐛 preserve file names from server forwards

kf_lib_data_ingest/common/file_retriever.py, kf_lib_data_ingest/etl/extract/extract.py, tests/test_extract_stage.py, tests/test_file_retriever.py
=> ♻️ Preserve original file's ext in fetched temp file

kf_lib_data_ingest/common/pandas_utils.py, kf_lib_data_ingest/etl/transform/auto.py, kf_lib_data_ingest/etl/transform/guided.py, kf_lib_data_ingest/etl/transform/transform.py, kf_lib_data_ingest/factory/templates/my_study/transform_module.py, tests/conftest.py, tests/data/test_study/transform_module.py, tests/data/test_study/transform_module_simple.py, tests/test_guided_transform.py, tests/test_null_processing.py, tests/test_pandas_utils.py, tests/test_transform_stage.py
=> ♻️ Refactor guided transform stage

scripts/build.sh
=> 🐛 Rm ingest test_study from build.sh

kf_lib_data_ingest/common/misc.py
=> 🐛 Use safe YAML loader

kf_lib_data_ingest/common/concept_schema.py, kf_lib_data_ingest/etl/extract/extract.py, kf_lib_data_ingest/target_apis/kids_first.py, tests/test_extract_stage.py
Get visibility right in transform.
If something is visible, then also record that it's not hidden, and vice versa.
fixes #218
=> ✨🐛 visibility attribute mirror

README.md
=> 📝  Clean up README

docs/source/index.rst, docs/source/tutorial/index.rst, docs/source/tutorial/ingest_package.rst, docs/source/tutorial/project_setup.rst
=> ♻️ Use term "ingest package" consistently in docs site

kf_lib_data_ingest/etl/load/load.py, kf_lib_data_ingest/target_apis/kids_first.py, tests/data/test_boyd_study/dataset_ingest_config.yml, tests/data/test_study/dataset_ingest_config.yml
Most of the feedback is log message related so best way is to run this for boyd to see what you think
=> 👌 Initial feedback load stage

kf_lib_data_ingest/app/cli.py, tests/test_ingest_pipeline.py
Addresses #188 and https://github.com/kids-first/kf-ingest-packages/issues/17
=> ✨ Add Test CLI cmd

Jenkinsfile
=> 👷 Add Jenkinsfile

dev-requirements.txt, requirements.txt
🐛 Add pytest to runtime requirements
♻️ Add runtime requirements to dev-requirements
=> 🐛 Add missing pytest and re-org dev-requirements

docs/data/family_and_phenotype.tsv, docs/source/index.rst, docs/source/tutorial/extract.rst, docs/source/tutorial/index.rst, docs/source/tutorial/package_testing.rst, docs/source/tutorial/project_setup.rst, docs/source/tutorial/transform.rst
Closes #236 and #154 
Could probably add a section on unique keys, but I'm going to leave this for another issue/PR.
=> 📝 Update tutorial - test ingest package, transform stg

docs/source/install.rst, docs/source/tutorial/ingest_package.rst, docs/source/tutorial/package_testing.rst, docs/source/tutorial/project_setup.rst, kf_lib_data_ingest/app/cli.py, kf_lib_data_ingest/config.py, kf_lib_data_ingest/etl/configuration/ingest_package_config.py, kf_lib_data_ingest/etl/configuration/transform_module.py, kf_lib_data_ingest/etl/ingest_pipeline.py, templates/my_study/ingest_package_config.py, tests/conftest.py, tests/data/SD_ME0WME0W/ingest_package_config.py, tests/data/test_boyd_study/ingest_package_config.py, tests/data/test_study/ingest_package_config.py, tests/test_configs.py, tests/test_ingest_pipeline.py
=> 🚚 dataset_ingest_config -> ingest_package_config

kf_lib_data_ingest/etl/configuration/base_config.py, kf_lib_data_ingest/etl/configuration/ingest_package_config.py, kf_lib_data_ingest/etl/ingest_pipeline.py, tests/test_configs.py
=> 🐛 expected_counts not required

CODEOWNERS
Until other people are more familiar with the project, I think one of us should be blockers on merging any PRs.
=> 🔒 lock down merges

kf_lib_data_ingest/app/settings/base.py, kf_lib_data_ingest/app/settings/development.py, kf_lib_data_ingest/app/settings/production.py, kf_lib_data_ingest/etl/configuration/log.py, kf_lib_data_ingest/network/oauth2.py
Keep auth-related environment variables out of logs.
closes #256
=> 🔒 No auth environment logging

kf_lib_data_ingest/network/utils.py, tests/data/funny name file €א.txt, tests/test_file_retriever.py
=> 🐛 fix extended-attr filename parsing bugs

kf_lib_data_ingest/common/file_retriever.py, kf_lib_data_ingest/network/utils.py
Closes #245, #255, and adds one more log statement for successful http file gets
=> 🐛 Fix logging with fetching files

docs/source/index.rst, docs/source/tutorial/app.rst, docs/source/tutorial/extract.rst, docs/source/tutorial/index.rst
=> ✨ Add app settings sect to docs

docs/source/tutorial/extract.rst, kf_lib_data_ingest/app/settings/development.py, tests/test_file_retriever.py
=> 🔧 Update dev settings - pass token in req header

kf_lib_data_ingest/common/misc.py, kf_lib_data_ingest/etl/extract/extract.py, kf_lib_data_ingest/etl/transform/guided.py
the df coming out of the user's custom transform code wasn't being cleaned
=> 🐛 Clean up the transform output df

kf_lib_data_ingest/etl/ingest_pipeline.py, tests/conftest.py, tests/test_app_settings.py, tests/test_oauth2.py, tests/test_pandas_utils.py, tests/test_user_def_tests.py
=> 🐛 Fix user defined test bugs

docs/source/tutorial/package_testing.rst, kf_lib_data_ingest/app/cli.py, kf_lib_data_ingest/common/concept_schema.py, kf_lib_data_ingest/common/stage.py, kf_lib_data_ingest/etl/extract/extract.py, kf_lib_data_ingest/etl/ingest_pipeline.py, kf_lib_data_ingest/etl/stage_analyses.py, kf_lib_data_ingest/etl/transform/guided.py, kf_lib_data_ingest/etl/transform/transform.py, tests/test_create_new_ingest.py, tests/test_ingest_pipeline.py, tests/test_logging.py
=> ✨ Post transform accounting

kf_lib_data_ingest/common/pandas_utils.py, kf_lib_data_ingest/etl/extract/extract.py, kf_lib_data_ingest/etl/ingest_pipeline.py, kf_lib_data_ingest/etl/transform/transform.py
gives things like `DataIngestPipeline - ERROR - TransformStage received no input. Did the previous stage produce anything?`
=> 🚸 Nicer handling of missing(stubbed) data

kf_lib_data_ingest/etl/stage_analyses.py, tests/test_stage_analyses.py
=> 🐛 Don't access attributes on strings

kf_lib_data_ingest/common/misc.py, tests/test_misc.py
=> 🐛 Fix numeric_to_str - vals that equate to 0 should return '0'

kf_lib_data_ingest/etl/transform/guided.py, kf_lib_data_ingest/etl/transform/transform.py, tests/test_transform_stage.py
=> ✨ Write transform stage output to TSV

docs/source/tutorial/debugging.rst, docs/source/tutorial/index.rst, kf_lib_data_ingest/app/cli.py, kf_lib_data_ingest/common/misc.py, kf_lib_data_ingest/common/stage.py, kf_lib_data_ingest/etl/ingest_pipeline.py, kf_lib_data_ingest/etl/load/load.py, tests/data/simple_study/data/clinical.tsv, tests/data/simple_study/extract_configs/extract_config.py, tests/data/simple_study/ingest_package_config.py, tests/data/simple_study/transform_module.py, tests/test_ingest_pipeline.py, tests/test_load_stage.py
Closes #37 
```
kidsfirst [test|ingest] --stages=[any subsequence of 'etl' without gaps in sequence]
```
=> ✨ Run subsets of ingest pipeline

docs/source/tutorial/transform.rst, kf_lib_data_ingest/config.py, kf_lib_data_ingest/etl/transform/guided.py, kf_lib_data_ingest/etl/transform/transform.py, templates/my_study/transform_module.py, tests/data/SD_ME0WME0W/transform_module.py, tests/data/simple_study/transform_module.py, tests/data/test_boyd_study/transform_module.py, tests/data/test_study/transform_module.py, tests/data/test_study/transform_module_simple.py, tests/test_guided_transform.py, tests/test_null_processing.py, tests/test_transform_stage.py
=> ♻️ Transform function outputs dict of DataFrames

kf_lib_data_ingest/etl/configuration/target_api_config.py, kf_lib_data_ingest/etl/load/load.py, kf_lib_data_ingest/etl/transform/guided.py, kf_lib_data_ingest/etl/transform/standard_model/model.py, kf_lib_data_ingest/etl/transform/transform.py, kf_lib_data_ingest/target_apis/kids_first.py, tests/test_guided_transform.py, tests/test_standard_model.py, tests/test_target_api_config.py
=> ♻️ Refactor links in target api cfg 

kf_lib_data_ingest/common/concept_schema.py, kf_lib_data_ingest/target_apis/kids_first.py
Please review #319 first, will change base after that merges. 
Closes #321
=> ✨ Add family relationship to concept schema and kids first api config

kf_lib_data_ingest/target_apis/kids_first.py
=> 🐛 Fix diagnosis event age concept

kf_lib_data_ingest/common/pandas_utils.py, tests/test_pandas_utils.py
=> 🐛 Fix merge col validation bug in merge_wo_duplicates

tests/test_file_retriever.py
The basic auth test wasn't making sure that the username and password actually got sent through. This fixes that.
closes #337
=> 🐛 Remove errant layer from basic auth test config

kf_lib_data_ingest/common/constants.py
=> ✨ Add ETag to constants

kf_lib_data_ingest/common/constants.py
This PR adds/updates constants across multiple entities.
=> 👷 Updates Constants

kf_lib_data_ingest/etl/configuration/target_api_config.py, kf_lib_data_ingest/etl/load/load.py, kf_lib_data_ingest/etl/transform/guided.py, kf_lib_data_ingest/target_apis/kids_first.py, tests/test_load_stage.py, tests/test_target_api_config.py
=> ✨ Add type mapping to target api config

kf_lib_data_ingest/etl/load/load.py, kf_lib_data_ingest/network/utils.py, tests/test_ingest_pipeline.py, tests/test_load_stage.py
Halt async loading on connection error. Closes 351 and 215.
=> 🐛 Exit on thread exception

kf_lib_data_ingest/etl/transform/guided.py, kf_lib_data_ingest/etl/transform/transform.py
=> 🐛 Make sure the interim output gets written

kf_lib_data_ingest/common/misc.py, kf_lib_data_ingest/etl/configuration/ingest_package_config.py, kf_lib_data_ingest/etl/extract/extract.py, kf_lib_data_ingest/etl/ingest_pipeline.py, tests/test_extract_stage.py
=> 🐛 Use relative path as extract output key instead of full path

kf_lib_data_ingest/common/constants.py
=> 💬 Add new datatype constants

kf_lib_data_ingest/common/concept_schema.py, kf_lib_data_ingest/common/misc.py, kf_lib_data_ingest/etl/extract/operations.py, kf_lib_data_ingest/target_apis/kids_first.py, tests/test_extract_operations.py
=> 🐛 Add GF ACLs to concepts and target_schema

kf_lib_data_ingest/etl/extract/operations.py, tests/test_extract_operations.py
closes #371 
¿What happens if I also say that it...
closes #372 ?
=> ✨ Let value_map take a regex pattern also

docs/source/challenge_scenarios/extracting/multifile_fusion.rst, kf_lib_data_ingest/common/datafile_readers.py, kf_lib_data_ingest/etl/extract/extract.py
Logic that was in the extract stage is now in datafile_readers, and the
readers are now smarter about binary vs ascii file modes.
closes #367 
closes #368
=> ♻️ Factor out pandas read file functions

kf_lib_data_ingest/common/pandas_utils.py, kf_lib_data_ingest/etl/extract/extract.py
convert DF column sets to lists, because otherwise they look ugly in the logs
=> 💬 Print column lists nicer

docs/archive/design/extract_config_format.py, docs/source/tutorial/extract.rst, kf_lib_data_ingest/etl/configuration/extract_config.py, kf_lib_data_ingest/etl/extract/extract.py, templates/my_study/extract_configs/extract_config.py, tests/data/SD_ME0WME0W/extract_configs/clinical.py, tests/data/SD_ME0WME0W/extract_configs/family_and_phenotype.py, tests/data/simple_study/extract_config_development.py, tests/data/simple_study/extract_config_production.py, tests/data/simple_study/extract_configs/extract_config.py, tests/data/test_boyd_study/extract_configs/Boyd_Minimal_Data_Elements_Cuellar_9-2-2018_EDITED_v2_map.py, tests/data/test_boyd_study/extract_configs/manifest_180917_rectified_map.py, tests/data/test_study/extract_configs/simple_tsv_example1.py, tests/data/test_study/extract_configs/simple_tsv_example2.py, tests/data/test_study/extract_configs/split_rows_tsv_example1.py, tests/data/test_study/extract_configs/unsimple_xlsx_example1.py, tests/test_extract_stage.py
This removes the terminology collision between "load/read" of files and "load/send" to endpoints. It also moves the read function setting out of the read params setting. Existing ingest packages will need to be updated.
=> ♻️💥 Change "load" to "read"

kf_lib_data_ingest/common/concept_schema.py
Needed for ingesting harmonized single specimen genomic files. See [here](https://github.com/kids-first/kf-ingest-packages/blob/3621e871a07a3daa55ee18a01ce0b353252ccd26/kf_ingest_packages/packages/SD_46SK55A3/extract_configs/chung_harm_gf_s3_obj_list.py#L39).
=> ✨ Add gf source file to concept schema

kf_lib_data_ingest/etl/ingest_pipeline.py
=> 🐛 Keep extracted UKs in comparison

Jenkinsfile, tests/conftest.py
I guess black improved between then and now
=> 🚨 Update black

docs/source/challenge_scenarios/extracting/multifile_fusion.rst, kf_lib_data_ingest/common/datafile_readers.py, kf_lib_data_ingest/common/io.py, kf_lib_data_ingest/common/misc.py, kf_lib_data_ingest/common/stage.py, kf_lib_data_ingest/etl/configuration/base_config.py, kf_lib_data_ingest/etl/extract/extract.py, kf_lib_data_ingest/etl/transform/transform.py, kf_lib_data_ingest/network/utils.py, templates/my_study/tests/conftest.py, tests/conftest.py, tests/test_datafile_readers.py, tests/test_io.py, tests/test_null_processing.py
You can care less about which reader function you need to use for which
file format when testing
=> ♻️ Move reader selector out of ExtractStage

kf_lib_data_ingest/common/io.py
This PR fixes file path access errors.
=> 🚧 Fix read_df Errors

docs/source/tutorial/extract/extract_example.inc, docs/source/tutorial/extract/index.rst, docs/source/tutorial/extract/map_custom_reader.inc, docs/source/tutorial/extract/map_preprocessing.inc
=> 📝 Make doc for custom reads more prominent

kf_lib_data_ingest/app/cli.py, kf_lib_data_ingest/app/settings/base.py, kf_lib_data_ingest/common/warehousing.py, kf_lib_data_ingest/etl/configuration/extract_config.py, kf_lib_data_ingest/etl/configuration/ingest_package_config.py, kf_lib_data_ingest/etl/configuration/log.py, kf_lib_data_ingest/etl/configuration/target_api_config.py, kf_lib_data_ingest/etl/configuration/transform_module.py, kf_lib_data_ingest/etl/extract/extract.py, kf_lib_data_ingest/etl/ingest_pipeline.py, kf_lib_data_ingest/etl/load/message_packer.py, kf_lib_data_ingest/etl/transform/guided.py, requirements.txt, tests/conftest.py, tests/test_message_packer.py, tests/test_stage_analyses.py
=> ✨ Add methods for sending data to a db

kf_lib_data_ingest/app/cli.py, kf_lib_data_ingest/common/warehousing.py, kf_lib_data_ingest/etl/ingest_pipeline.py
Gives ingest schemas a common prefix so that they can be properly removed and then also the package directory so that studies can have multiple packages.
=> 🐛 Fix some missing/broken bits of warehousing

kf_lib_data_ingest/common/pandas_utils.py, tests/test_pandas_utils.py
=> 🐛 Unbreak outer_merge with multiple join cols

kf_lib_data_ingest/common/concept_schema.py
added an enrollment age concept to handle when age there is an age at enrollment variable
=> ✨ Add enrollment age concept

docs/source/tutorial/extract/extract_example.inc
=> ✏️ Fix bad link in doc

kf_lib_data_ingest/app/cli.py, kf_lib_data_ingest/app/settings/__init__.py, kf_lib_data_ingest/common/file_retriever.py, kf_lib_data_ingest/common/misc.py, kf_lib_data_ingest/common/pandas_utils.py, kf_lib_data_ingest/common/stage.py, kf_lib_data_ingest/common/type_safety.py, kf_lib_data_ingest/etl/configuration/target_api_config.py, kf_lib_data_ingest/etl/extract/extract.py, kf_lib_data_ingest/etl/extract/operations.py, kf_lib_data_ingest/etl/ingest_pipeline.py, kf_lib_data_ingest/etl/load/load.py, kf_lib_data_ingest/etl/load/message_packer.py, kf_lib_data_ingest/etl/transform/guided.py, kf_lib_data_ingest/etl/transform/transform.py, kf_lib_data_ingest/network/oauth2.py, kf_lib_data_ingest/network/utils.py
edited docstrings to be in rst
closes #17
=> ✏️Refactored docstrings to all be in RST format

kf_lib_data_ingest/common/concept_schema.py, kf_lib_data_ingest/target_apis/kids_first.py
=> 🚧 Add sample procurement

docs/source/install.rst
=> 📝 Add psycopg2 to the install instructions

kf_lib_data_ingest/config.py, kf_lib_data_ingest/network/utils.py
=> ✨ Customize requests user agent

CHANGELOG.md, release_maker_cfg.json
- Emojis: ♻️ x1, ⬆️ x1, 🔇 x1, 🍱 x1, 👽 x1, ✨ x1, 🚨 x2, 🐛 x1, 📝 x1, 🚧 x1, 💡 x1
- Categories: Other Changes x3, Ops x1, Removals x1, Fixes x4, Additions x1, Documentation x2
- [#458](https://github.com/kids-first/kf-lib-data-ingest/pull/458) - ♻️ Refactor target entity construction into plugin API - [d753e5d2](https://github.com/kids-first/kf-lib-data-ingest/commit/d753e5d2d9a0a23a75a390625ab53ed60910de93) by [fiendish](https://github.com/fiendish)
- [#467](https://github.com/kids-first/kf-lib-data-ingest/pull/467) - ⬆️ Upgrade boto3 and pandas - [4f3370d7](https://github.com/kids-first/kf-lib-data-ingest/commit/4f3370d71ebd3c46a19ac936653376196c10af33) by [fiendish](https://github.com/fiendish)
- [#465](https://github.com/kids-first/kf-lib-data-ingest/pull/465) - 🔇 Censor more strings from …
=> 🏷 Release 0.11.0

kf_lib_data_ingest/common/constants.py, kf_lib_data_ingest/validation/test_input_structure.py, kf_lib_data_ingest/validation/values.py
Closes #479 
Wasn't sure exactly where to put the file. Created a `validation` folder for it. Added some constants to the `common.constants.py` file that appear in data tracker. This won't pass the CircleCI test because flake8 doesn't like lambda functions (`E731`).
=> ✨ Define validation test input structure

kf_lib_data_ingest/common/stage.py, kf_lib_data_ingest/etl/ingest_pipeline.py, kf_lib_data_ingest/etl/stage_analyses.py, kf_lib_data_ingest/templates/my_study/tests/conftest.py, kf_lib_data_ingest/templates/my_study/tests/test_custom_counts.py, tests/test_create_new_ingest.py, tests/test_ingest_pipeline.py, tests/test_logging.py, tests/test_stage_analyses.py
I accidentally merged this into the `master` branch instead of the `master-validation` branch!
Reverts kids-first/kf-lib-data-ingest#492
=> Revert "🔥 Remove old accounting code"

kf_lib_data_ingest/app/cli.py, kf_lib_data_ingest/common/io.py, kf_lib_data_ingest/validation/validation.py, tests/test_validation.py
Closes #491 
Adds skeleton code required to perform validation with `kidsfirst validate` CLI command.
=> ✨🚧Create skeleton code for CLI validate command

kf_lib_data_ingest/common/io.py, requirements.txt, tests/test_io.py
=> 🐛 Detect encodings of files when reading

kf_lib_data_ingest/app/cli.py, kf_lib_data_ingest/common/stage.py, kf_lib_data_ingest/etl/ingest_pipeline.py, kf_lib_data_ingest/etl/load/load.py, kf_lib_data_ingest/validation/data_validator.py, kf_lib_data_ingest/validation/validation.py, requirements.txt, tests/conftest.py, tests/test_ingest_pipeline.py, tests/test_logging.py, tests/test_validation.py
=> ✨ Integrate data validation into ingest pipeline

kf_lib_data_ingest/etl/transform/guided.py, kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py, tests/test_guided_transform.py
=> ♻️ Auto-populate BIOSPECIMEN|ID, BIOSPECIMEN_GROUP|ID cols

kf_lib_data_ingest/common/concept_schema.py, kf_lib_data_ingest/common/constants.py, kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py, kf_lib_data_ingest/validation/values.py
Flexibly handle ages entered as split value/unit columns.
closes #494
=> 💬 Add concepts for participant template 

docs/source/tutorial/extract/extract_example.inc
Closes https://github.com/kids-first/kf-lib-data-ingest/issues/516
=> 📝 import Split() in docs extract config

kf_lib_data_ingest/validation/reporting/markdown.py
Closes #519 
Results look like this:
=> 🎨 Display test result summary as table

kf_lib_data_ingest/etl/load/load_v1.py, kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py
=> 🐛 Correct study ID/TARGET_SERVICE_ID overwrite

kf_lib_data_ingest/app/settings/development.py, kf_lib_data_ingest/app/settings/production.py
=> 👽 Add auth configs for new study creator subdomains

kf_lib_data_ingest/validation/data_validator.py, kf_lib_data_ingest/validation/values.py
=> 🐛 Don't show blank cells as invalid values

kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py
=> 🐛 Fix bad call order blocking BS and SE loads

kf_lib_data_ingest/common/constants.py
This sequencing center was used to sequence samples for a single participant that is under cbtn, with dipg, and went through the pnoc008 workflows.
=> ✨ Add Ashion Sequencing center to constants.py

.circleci/config.yml, dev-requirements.txt, kf_lib_data_ingest/common/constants.py, requirements.txt, tests/test_file_retriever.py
The big one is xlrd which is broken in 3.9 for a terrible reason.
=> ⬆️ Update dependencies for Python 3.9

kf_lib_data_ingest/validation/reporting/markdown.py
=> 🐛 Escape strings before adding to markdown

kf_lib_data_ingest/validation/reporting/base.py, kf_lib_data_ingest/validation/reporting/html.py, kf_lib_data_ingest/validation/reporting/markdown.py, kf_lib_data_ingest/validation/reporting/table.py, kf_lib_data_ingest/validation/validation.py, requirements.txt
Generated from the markdown with some github-ish css. This is for #512 because the other report formats require special tools to be useful to humans.
=> 🔊 Add html validation report

doc-requirements.txt
=> 💚 Fix sphinx theme install egg name

kf_lib_data_ingest/common/constants.py
=> add_sickkids_sc

kf_lib_data_ingest/common/misc.py, kf_lib_data_ingest/etl/extract/extract.py, tests/test_extract_stage.py
=> 🥅 Error if read DF is empty

kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py
The dataservice could be lying about the sizes of fields like it does for the genomic file size field.
So instead of nulling the field, print a guiding message in case the next submission fails.
=> 🐛 Don't nullify coerced integers

kf_lib_data_ingest/etl/configuration/target_api_config.py, tests/data/bad_v1api.py, tests/data/bad_v2api.py, tests/test_target_api_config.py
=> 🐛 Validate V1 API configurations

.github/workflows/publish.yml
Fixing issue https://github.com/kids-first/kf-lib-data-ingest/issues/573
=> 💚 Remove requirement for job in testing workflow

kf_lib_data_ingest/etl/extract/extract.py
The reference moved when documentation was updated.
=> 🔊 Update nested sublists log notice URL

docs/source/tutorial/ingest_package.rst, kf_lib_data_ingest/app/cli.py, kf_lib_data_ingest/common/concept_schema.py, kf_lib_data_ingest/common/warehousing.py, kf_lib_data_ingest/etl/configuration/ingest_package_config.py, kf_lib_data_ingest/etl/extract/extract.py, kf_lib_data_ingest/etl/ingest_pipeline.py, kf_lib_data_ingest/etl/load/load_v1.py, kf_lib_data_ingest/factory/generate.py, kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py, kf_lib_data_ingest/templates/my_ingest_package/ingest_package_config.py, kf_lib_data_ingest/validation/data_validator.py, kf_lib_data_ingest/validation/default_hierarchy.py, tests/data/simple_study/ingest_package_config.py, tests/test_configs.py
Not everyone pre-registers their studies, so we shouldn't rely on Study target service identifiers being available. 
closes #577
=> ✨ Enable loading un-preregistered Studies

kf_lib_data_ingest/common/pandas_utils.py, kf_lib_data_ingest/etl/extract/extract.py, kf_lib_data_ingest/etl/extract/operations.py, kf_lib_data_ingest/etl/ingest_pipeline.py, tests/test_extract_operations.py, tests/test_extract_stage.py
=> ✨ Allow some extract operations to be optional

CHANGELOG.md
- Emojis: 🐛 x1
- Categories: Fixes x1
- [#587](https://github.com/kids-first/kf-lib-data-ingest/pull/587) - 🐛 Don't error on relation external_id without key fields - [c1f582a6](https://github.com/kids-first/kf-lib-data-ingest/commit/c1f582a6f0aae69e0300748326a9e1d91246746d) by [fiendish](https://github.com/fiendish)
=> 🏷 Release 1.2.1

kf_lib_data_ingest/common/constants.py
Add new SC KF ID.
SC KF ID: SC_75KENA7A
Name: Humangenetik Tübingen
=> add_SC_75KENA7A

kf_lib_data_ingest/etl/extract/extract.py, kf_lib_data_ingest/etl/extract/utils.py, tests/test_extract_stage.py
=> ✨ Standalone Extractor

CHANGELOG.md
- Emojis: 🐛 x1
- Categories: Fixes x1
- [#598](https://github.com/kids-first/kf-lib-data-ingest/pull/598) - 🐛 Change ValueError to Exception - [b23eedf1](https://github.com/kids-first/kf-lib-data-ingest/commit/b23eedf1680d13348080d1119f39a0311a98d978) by [Christina-J-Diaz](https://github.com/Christina-J-Diaz)
=> 🏷 Release 1.4.1

CHANGELOG.md
- Emojis: 🔧 x1, 🔊 x1
- Categories: Additions x1, Other Changes x1
- [#602](https://github.com/kids-first/kf-lib-data-ingest/pull/602) - 🔧 Fix Homo sapiens casing - [bec35656](https://github.com/kids-first/kf-lib-data-ingest/commit/bec356564a3181a0bfe69163824cc1e85c53e94c) by [liberaliscomputing](https://github.com/liberaliscomputing)
- [#603](https://github.com/kids-first/kf-lib-data-ingest/pull/603) - 🔊 Rearrange target ID inquiry to improve load logging - [826b9ba2](https://github.com/kids-first/kf-lib-data-ingest/commit/826b9ba202e207a50902dca97b9c6047ec779464) by [fiendish](https://github.com/fiendish)
=> 🏷 Release 1.6.0

CHANGELOG.md
- Emojis: 💡 x1, ⬆️ x1, 💥 x1
- Categories: Documentation x1, Ops x1, Other Changes x1
- [#607](https://github.com/kids-first/kf-lib-data-ingest/pull/607) - 💡 Tweak test command docstring - [87e51f9b](https://github.com/kids-first/kf-lib-data-ingest/commit/87e51f9bc30abf8acebee8df88def13ccd678caa) by [fiendish](https://github.com/fiendish)
- [#606](https://github.com/kids-first/kf-lib-data-ingest/pull/606) - ⬆️ Update moto to remove test warning - [d883114c](https://github.com/kids-first/kf-lib-data-ingest/commit/d883114c64f088379439fa94efcd660a1fc40d91) by [fiendish](https://github.com/fiendish)
- [#605](https://github.com/kids-first/kf-lib-data-ingest/pull/605) - 💥 Only one outcome per patient now - [b3724f41](https://github.com/kids-first/kf-lib-data-ingest/commit/b3724f41615fe3306da80861 …
=> 🏷 Release 1.7.0

CHANGELOG.md
- Emojis: 📦 x1
- Categories: Ops x1
- [#609](https://github.com/kids-first/kf-lib-data-ingest/pull/609) - 📦 Make installable from gh release zip/tar - [5ee7431d](https://github.com/kids-first/kf-lib-data-ingest/commit/5ee7431d68b645e98c1a84e037f2d369832cc8f0) by [fiendish](https://github.com/fiendish)
=> 🏷 Release 1.7.1

CHANGELOG.md
- Emojis: ✨ x1
- [#597](https://github.com/kids-first/kf-lib-data-ingest/pull/597) - ✨ New functionality to support Data Tracker templates - [f9ad6833](https://github.com/kids-first/kf-lib-data-ingest/commit/f9ad6833f974f24dcdefc9e09b57eaa5a5884097) by [znatty22](https://github.com/znatty22)
=> 🏷 Release 1.8.0

CHANGELOG.md
- Emojis: 🚸 x1, ✏️ x1
- Categories: Fixes x2
- [#615](https://github.com/kids-first/kf-lib-data-ingest/pull/615) - 🚸 Improve CLI help availability - [34f3e0ec](https://github.com/kids-first/kf-lib-data-ingest/commit/34f3e0ec7ad6f0662906506e8a186cac2ea1f19c) by [fiendish](https://github.com/fiendish)
- [#614](https://github.com/kids-first/kf-lib-data-ingest/pull/614) - ✏️ Make hash names lower case & no special characters - [19613c71](https://github.com/kids-first/kf-lib-data-ingest/commit/19613c710a8cbadb9de5cb8316576facf0b6dbc4) by [chris-s-friedman](https://github.com/chris-s-friedman)
=> 🏷 Release 1.8.1

CHANGELOG.md
- Emojis: 🐛 x1, ♻️ x1
- Categories: Fixes x1, Other Changes x1
- [#618](https://github.com/kids-first/kf-lib-data-ingest/pull/618) - 🐛 Assign IDs to new entities in dry_run mode that can be re-used during the run - [f1e304d3](https://github.com/kids-first/kf-lib-data-ingest/commit/f1e304d3b08d1a0d9eed183f7a4ba9d06de226c2) by [fiendish](https://github.com/fiendish)
- [#616](https://github.com/kids-first/kf-lib-data-ingest/pull/616) - ♻️ Separate load base from v1/v2 for clarity - [d6451e92](https://github.com/kids-first/kf-lib-data-ingest/commit/d6451e92d8e8cf35076550c93663a7d7d01377f7) by [fiendish](https://github.com/fiendish)
=> 🏷 Release 1.8.2

CHANGELOG.md
- Emojis: ⬆️ x1
- Categories: Ops x1
- [#620](https://github.com/kids-first/kf-lib-data-ingest/pull/620) - ⬆️ Flex the pytest dep version pin and fix boundary specs - [8755cb80](https://github.com/kids-first/kf-lib-data-ingest/commit/8755cb80db3beeeabab87b083f43ea7ff3663a92) by [fiendish](https://github.com/fiendish)
=> 🏷 Release 1.8.3

docs/source/design/warehousing.rst, docs/source/install.rst, docs/source/tutorial/testing.rst, kf_lib_data_ingest/app/cli.py
=> 🚸 Warehousing is no longer default behavior

CHANGELOG.md
- Emojis: 🚸 x1
- Categories: Fixes x1
- [#622](https://github.com/kids-first/kf-lib-data-ingest/pull/622) - 🚸 Warehousing is no longer default behavior - [ef3d4bba](https://github.com/kids-first/kf-lib-data-ingest/commit/ef3d4bba9ae78573e569626924a140e5931e6cda) by [fiendish](https://github.com/fiendish)
=> 🏷 Release 1.9.0

kf_lib_data_ingest/validation/reporting/markdown.py, tests/test_validation.py
=> ✨ Optionally exclude tests from validation report

kf_lib_data_ingest/etl/extract/utils.py, tests/test_extract_stage.py
=> 🐛 Fix VISIBLE/HIDDEN obversion to work with strings as expected

CHANGELOG.md
- Emojis: 🐛 x2, ✨ x1, 🥅 x1, 📝 x1
- Categories: Additions x1, Documentation x1, Fixes x3
- [#635](https://github.com/kids-first/kf-lib-data-ingest/pull/635) - 🐛 Fix VISIBLE/HIDDEN obversion to work with strings as expected - [8ee33322](https://github.com/kids-first/kf-lib-data-ingest/commit/8ee3332256b568eeaa2c10e11a6dad3059623897) by [fiendish](https://github.com/fiendish)
- [#637](https://github.com/kids-first/kf-lib-data-ingest/pull/637) - ✨ Optionally exclude tests from validation report - [042ebe97](https://github.com/kids-first/kf-lib-data-ingest/commit/042ebe972a8409824305b5cc8edceb854925152d) by [znatty22](https://github.com/znatty22)
- [#633](https://github.com/kids-first/kf-lib-data-ingest/pull/633) - 🥅 Report more useful info for load value errors - …
=> 🏷 Release 1.10.0

kf_lib_data_ingest/common/constants.py
Add NIH as SEQUENCING.CENTER.NIH and Methylation as SEQUENCING.STRATEGY.METHYL
=> ✨ Add NIH and Methylation constants

kf_lib_data_ingest/common/constants.py
=> ✨ Add new sequencing center Tempus

CHANGELOG.md
- Emojis: ? x3, ✨ x3
- Categories: Additions x3, Other Changes x3
- [#645](https://github.com/kids-first/kf-lib-data-ingest/pull/645) -  add gru-npu consent group - [1da6dd79](https://github.com/kids-first/kf-lib-data-ingest/commit/1da6dd79478674495e60fe22ccd0d95b71892fb4) by [chris-s-friedman](https://github.com/chris-s-friedman)
- [#644](https://github.com/kids-first/kf-lib-data-ingest/pull/644) -  :sparkles: specify external IDs for clinical markers - [c1f6c1c2](https://github.com/kids-first/kf-lib-data-ingest/commit/c1f6c1c220b5f4457f4a406be51d037697624dab) by [chris-s-friedman](https://github.com/chris-s-friedman)
- [#643](https://github.com/kids-first/kf-lib-data-ingest/pull/643) - ✨ Add new sequencing center Tempus - [87f5cdfb](https://github.com/kids-first/kf-lib-data-ingest/commit …
=> 🏷 Release 1.11.0

CHANGELOG.md
- Emojis: ✨ x1
- [#647](https://github.com/kids-first/kf-lib-data-ingest/pull/647) - ✨ Add Uberon - [aa5c807e](https://github.com/kids-first/kf-lib-data-ingest/commit/aa5c807eab5a98308e91d4277ae0702f95292f0b) by [liberaliscomputing](https://github.com/liberaliscomputing)
=> 🏷 Release 1.12.0

CHANGELOG.md
- Emojis: 🔧 x1, 📝 x1, 👷‍♀️ x1
- Categories: Documentation x1, Ops x1, Other Changes x1
- [#655](https://github.com/kids-first/kf-lib-data-ingest/pull/655) - 🔧 Add sequencing_experiment fields to target api config and add library_prep and selection to constants - [856b3e6b](https://github.com/kids-first/kf-lib-data-ingest/commit/856b3e6b6ce1671ee7e682267b9e8a9aed9f0325) by [chris-s-friedman](https://github.com/chris-s-friedman)
- [#653](https://github.com/kids-first/kf-lib-data-ingest/pull/653) - 📝 add documentation on adding custom logs - [002f65bc](https://github.com/kids-first/kf-lib-data-ingest/commit/002f65bc8da603492ed8aa33a91a8dcaca55647f) by [chris-s-friedman](https://github.com/chris-s-friedman)
- [#654](https://github.com/kids-first/kf-lib-data-ingest/pull/654) - 👷‍♀️ Fix CI …
=> 🏷 Release 1.13.0

kf_lib_data_ingest/common/constants.py
add New York Genome Center to sequencing center constants
=> 🔧 add nygc to sequencing centers and scRNA seq experiment strategy

CHANGELOG.md
- Emojis: 🔧 x1, ✨ x2
- Categories: Additions x2, Ops x1
- [#661](https://github.com/kids-first/kf-lib-data-ingest/pull/661) - 🔧 add nygc to sequencing centers and scRNA seq experiment strategy - [f40da348](https://github.com/kids-first/kf-lib-data-ingest/commit/f40da3482e789140139c461a36a145064a92e8c7) by [calkinsh](https://github.com/calkinsh)
- [#658](https://github.com/kids-first/kf-lib-data-ingest/pull/658) - ✨ Add Krantz-CDL-FY21-RNA constants to kflib - [b487540d](https://github.com/kids-first/kf-lib-data-ingest/commit/b487540d132bd7da94dc5823951a4f2860383b5e) by [r3m0chop](https://github.com/r3m0chop)
- [#657](https://github.com/kids-first/kf-lib-data-ingest/pull/657) - ✨ Add Letra-MNC-FY21 constants to kflib - [326163fb](https://github.com/kids-first/kf-lib-data-ingest/commit/32616 …
=> 🏷 Release 1.14.0

CHANGELOG.md
- Emojis: ? x1
- Categories: Other Changes x1
- [#665](https://github.com/kids-first/kf-lib-data-ingest/pull/665) -  :sparkles: add snRNAseq experiment strategy - [ab6d7baf](https://github.com/kids-first/kf-lib-data-ingest/commit/ab6d7bafb345be670350d1e569e66656f33e1f9f) by [calkinsh](https://github.com/calkinsh)
=> 🏷 Release 1.15.0

CHANGELOG.md
- Emojis: ✨ x1
- [#664](https://github.com/kids-first/kf-lib-data-ingest/pull/664) - ✨ create concepts for visibility reason and comment - [f2dc03fb](https://github.com/kids-first/kf-lib-data-ingest/commit/f2dc03fbb86f67a8c45f708464a5500e07293625) by [chris-s-friedman](https://github.com/chris-s-friedman)
=> 🏷 Release 1.16.0

kf_lib_data_ingest/validation/values.py
need to add new values to validation folder
=> :heavy_plus_sign: adding values to validation

kf_lib_data_ingest/validation/values.py
adding another value for long reads ingest that was previously missed
'ONT WGS'
=> :heavy_plus_sign: adding ONT strategy

kf_lib_data_ingest/common/constants.py
Add the genedx sequencing center
=> ✨ Add genedx sequencing center

CHANGELOG.md
- Emojis: ♻️ x1, ✨ x1, ? x3
- Categories: Additions x2, Other Changes x3
- [#663](https://github.com/kids-first/kf-lib-data-ingest/pull/663) - ♻️ Replace acl field with new authz - [f7efae76](https://github.com/kids-first/kf-lib-data-ingest/commit/f7efae76035849a157d7fc800e8f0260524784ad) by [znatty22](https://github.com/znatty22)
- [#671](https://github.com/kids-first/kf-lib-data-ingest/pull/671) - ✨ Add genedx sequencing center - [ad2f5322](https://github.com/kids-first/kf-lib-data-ingest/commit/ad2f53228cb7f19d0575790157ae52e032f62637) by [chris-s-friedman](https://github.com/chris-s-friedman)
- [#670](https://github.com/kids-first/kf-lib-data-ingest/pull/670) -  :heavy_plus_sign: adding ONT strategy - [799684c1](https://github.com/kids-first/kf-lib-data-ingest/commit/799684c1f8ae6fb1ee …
=> 🏷 Release 1.17.0

CHANGELOG.md
- Emojis: ? x1
- Categories: Other Changes x1
- [#674](https://github.com/kids-first/kf-lib-data-ingest/pull/674) -  :bug: Don't leave out visibility info in family relationships load - [7268dab8](https://github.com/kids-first/kf-lib-data-ingest/commit/7268dab8f87c6919384f909672bd423f6a58f6f0) by [znatty22](https://github.com/znatty22)
=> 🏷 Release 1.18.0

CHANGELOG.md
- Emojis: ? x1
- Categories: Other Changes x1
- [#676](https://github.com/kids-first/kf-lib-data-ingest/pull/676) -  :sparkles: add princess maxima center - [93b5901e](https://github.com/kids-first/kf-lib-data-ingest/commit/93b5901e7bea8337a6c6ef7134cf87e7adf7148c) by [HuangXiaoyan0106](https://github.com/HuangXiaoyan0106)
=> 🏷 Release 1.19.0

kf_lib_data_ingest/common/concept_schema.py, kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py
Extracts new fields in https://github.com/kids-first/kf-api-dataservice/pull/650
=> ✨ Add new SE, GF fields to KF Target API Plugin

CHANGELOG.md
- Emojis: ✨ x1
- [#678](https://github.com/kids-first/kf-lib-data-ingest/pull/678) - ✨ Add new SE, GF fields to KF Target API Plugin - [f31fa54c](https://github.com/kids-first/kf-lib-data-ingest/commit/f31fa54cf2ed44fd433dcc3f3fdfa4026f3f87e0) by [znatty22](https://github.com/znatty22)
=> 🏷 Release 1.20.0

kf_lib_data_ingest/common/constants.py
Add the UCSF CAT center
```
{
"_links":{
"biospecimens":"/biospecimens?sequencing_center_id=SC_MSQP04K7",
"collection":"/sequencing-centers",
"self":"/sequencing-centers/SC_MSQP04K7",
"sequencing_experiments":"/sequencing-experiments?sequencing_center_id=SC_MSQP04K7"
},
"_status":{
"code":201,
"message":"sequencing_center SC_MSQP04K7 created"},
"results":{
"created_at":"2024-05-30T03:12:37.574352+00:00",
"external_id":null,
"kf_id":"SC_MSQP04K7",
"modified_at":"2024-05-30T03:12:37.574360+00:00",
"name":"UCSF CAT",
"visibility_comment":null,
"visibility_reason":null,
"visible":true}
}
```
=> :wrench: add ucsf center

CHANGELOG.md
- Emojis: ✨ x2, ? x2
- Categories: Additions x2, Other Changes x2
- [#686](https://github.com/kids-first/kf-lib-data-ingest/pull/686) - ✨ D3B-586 sample relationship - [7cb601c3](https://github.com/kids-first/kf-lib-data-ingest/commit/7cb601c345e2e430887f7d1603ee7c2ae36bf74d) by [chris-s-friedman](https://github.com/chris-s-friedman)
- [#683](https://github.com/kids-first/kf-lib-data-ingest/pull/683) - ✨ Add Sample Concept - [026ed61c](https://github.com/kids-first/kf-lib-data-ingest/commit/026ed61c0708c25b9af418dbc1f013c4615bd8f7) by [chris-s-friedman](https://github.com/chris-s-friedman)
- [#684](https://github.com/kids-first/kf-lib-data-ingest/pull/684) -  :wrench: add ucsf center - [469d0974](https://github.com/kids-first/kf-lib-data-ingest/commit/469d097490aafea14dbd4f81d47fc8d6c6a6ca …
=> 🏷 Release 1.21.0

CHANGELOG.md
- Emojis: ? x1
- Categories: Other Changes x1
- [#687](https://github.com/kids-first/kf-lib-data-ingest/pull/687) -  :bug: Don't assume sample_id exists, since fk is optional on BS - [d020d455](https://github.com/kids-first/kf-lib-data-ingest/commit/d020d455aa5c147f94aa6c1a7b838f1655ac1e6f) by [znatty22](https://github.com/znatty22)
=> 🏷 Release 1.22.0

CHANGELOG.md
- Emojis: 🐛 x1, ? x1
- Categories: Fixes x1, Other Changes x1
- [#690](https://github.com/kids-first/kf-lib-data-ingest/pull/690) - 🐛 Round 2 - fix sample relationship loading - [70c738f6](https://github.com/kids-first/kf-lib-data-ingest/commit/70c738f6d57e80db04be5cf5abad20a93dc5d7e9) by [znatty22](https://github.com/znatty22)
- [#689](https://github.com/kids-first/kf-lib-data-ingest/pull/689) -  :bug: Fix SampleRelationship target ID lookup - [7cdcef2c](https://github.com/kids-first/kf-lib-data-ingest/commit/7cdcef2c6421a27805316ba6c1a9ab8e563431d5) by [znatty22](https://github.com/znatty22)
=> 🏷 Release 1.23.0

CHANGELOG.md
- Emojis: 🚑️ x1, 📌 x1
- Categories: Ops x1, Other Changes x1
- [#692](https://github.com/kids-first/kf-lib-data-ingest/pull/692) - 🚑️ Fix typo in kf target_api_plugin - [6b7fc637](https://github.com/kids-first/kf-lib-data-ingest/commit/6b7fc63794fee1ab9d2203ce48c8477656e9d680) by [chris-s-friedman](https://github.com/chris-s-friedman)
- [#693](https://github.com/kids-first/kf-lib-data-ingest/pull/693) - 📌 Pin numpy to 1.x to prevent python 3.9 issues - [e05591af](https://github.com/kids-first/kf-lib-data-ingest/commit/e05591af394e72164ed8d92168ac0eb81fb884f6) by [chris-s-friedman](https://github.com/chris-s-friedman)
=> 🏷 Release 1.23.1

CHANGELOG.md
- Emojis: ✨ x3
- Categories: Additions x3
- [#695](https://github.com/kids-first/kf-lib-data-ingest/pull/695) - ✨ AD-2303 add amount and amount units to sample and bs and kf target - [159b4cca](https://github.com/kids-first/kf-lib-data-ingest/commit/159b4ccaf5f94990ff71d7b1f259c1677172c0e4) by [chris-s-friedman](https://github.com/chris-s-friedman)
- [#696](https://github.com/kids-first/kf-lib-data-ingest/pull/696) - ✨ D3B-725 add has_match_normal and external_collection_id - [2abcf8b4](https://github.com/kids-first/kf-lib-data-ingest/commit/2abcf8b42cdbe5a7de6293ea59be9dd2d2343a2b) by [chris-s-friedman](https://github.com/chris-s-friedman)
- [#697](https://github.com/kids-first/kf-lib-data-ingest/pull/697) - ✨ D3B-674 add new CAVATICA gf fields - …
=> 🏷 Release 1.24.0

CHANGELOG.md
- Emojis: 👔 x1
- [#699](https://github.com/kids-first/kf-lib-data-ingest/pull/699) -  👔add upenn - [16263096](https://github.com/kids-first/kf-lib-data-ingest/commit/16263096c28bbd835708ae199e2c705bc6c6185f) by [HuangXiaoyan0106](https://github.com/HuangXiaoyan0106)
=> 🏷 Release 1.25.0
