kids-first/kf-lib-data-ingest

dev-requirements.txt
requirements.txt
tests/conftest.py
tests/data/test_boyd_study/extract_configs/Boyd_Minimal_Data_Elements_Cuellar_9-2-2018_EDITED_v2_map.py
tests/data/test_boyd_study/extract_configs/manifest_180917_rectified_map.py
tests/data/test_boyd_study/extract_configs/s3_files_kf-seq-data-hudsonalpha_haib17SB5136_map.py
tests/data/test_study/extract_configs/simple_tsv_example1.py
tests/data/test_study/extract_configs/simple_tsv_example2.py
tests/data/test_study/extract_configs/unsimple_xlsx_example1.py
tests/test_extract_stage.py
tests/test_target_api_config.py

New analysis revealed the proper way to interpret their manifest file which shows that they released new specimens without updating the IDs in their data file.
This is an interesting change, because it pulls in data from a second file in order to adjust values in the first.
I'm also updating the moto and boto3 dependencies because for some reason I keep getting incompatibility errors with the previous pinned versions.

🔧 Boyd study changes

---

kf_lib_data_ingest/etl/ingest_pipeline.py
kf_lib_data_ingest/etl/load/load.py
kf_lib_data_ingest/etl/transform/transform.py
tests/test_standard_model.py
tests/test_transform_stage.py

Part 1 of #95 
Previously the load stage was invoking a part of the transformation (from concept graph to target entities). We want to move this responsibility into the transformation stage and ensure that the load stage only deals with transmitting the target entities coming out of transform stage into the target service. 
This will allow us to interchange the transformation approach at runtime (auto transform via graph or guided transform via user supplied transform function).

♻️ Minor refactor transform, load

---

kf_lib_data_ingest/common/pandas_utils.py
tests/test_pandas_utils.py

Would like to have this merged before #101 , so that I can use these functions when writing and testing the user defined transform functions.
- Add `merge_wo_duplicates`, merge two dataframes into a single dataframe with no duplicate columns. Slightly modified version of [this](https://github.com/kids-first/kf-study-imports/blob/1429f8b538cb60fe47174cc7025daf219432f7f5/Avi/pandas_utils.py#L54)
- Add `outer_merge`, outer merge two dataframes and optionally return debugging dataframes

✨Add merge functions to pandas utils

---

kf_lib_data_ingest/common/stage.py
kf_lib_data_ingest/etl/ingest_pipeline.py
tests/test_extract_stage.py

This PR will standardize the structure of pipeline outputs.
-  Base `stage.py` handles creation of its output dir and names it using its class name. 
Output dir structure will be
```
<study dir>/
output/
<stage class name>/
- output_1.tsv
- output_2.txt
- ...  
```
Current example: 
```
tests/data/test_study/
output/
ExtractStage/
- ExtractStage_cache.txt
TransformStage/
LoadStage/ 
```

♻️ Refactor stage read write

---

dev-requirements.txt
doc-requirements.txt
scripts/build.sh
scripts/test.sh
tests/test_file_retriever.py

- For all CI scripts, always abort on non-zero exit code from any of the things running in the script
- Upgrade pip and install egg info before installing reqs
- See https://github.com/pypa/pip/issues/4537 for more details
- Fix recurring S3 related error in file retriever test
thanks @fiendish !

👷 Fix CI Scripts

---

kf_lib_data_ingest/common/file_retriever.py
tests/test_file_retriever.py

Addresses #122.
will still error, but the error will be expected instead of unexpected

🐛 Fix for #122. Helpful error instead of unhelpful error on missing file protocol.

---

kf_lib_data_ingest/common/pandas_utils.py

remove the inplace assignment in dropna to squelch the dumb warning
```
tests/test_pandas_utils.py::test_outer_merge
kf_lib_data_ingest/common/pandas_utils.py:286: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame
See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
df.dropna(how="all", inplace=True)
-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

🚨 Pandas's SettingWithCopyWarning is so annoying

---

kf_lib_data_ingest/cli.py
kf_lib_data_ingest/config.py
kf_lib_data_ingest/etl/configuration/dataset_ingest_config.py
kf_lib_data_ingest/etl/configuration/log.py
kf_lib_data_ingest/etl/ingest_pipeline.py
tests/test_logging.py

Addresses part of #158 
- We were doing weird things with the log_level before. Now we use str log levels in inputs (CLI opts, dataset_ingest_config, etc) and then later on we convert to int version of the log level during setup of the logger
- Add log_level CLI option which overrides the log_level set in `dataset_ingest_config.yml`

✨ Small Logging Improvements

---

tests/data/test_boyd_study/extract_configs/Boyd_Minimal_Data_Elements_Cuellar_9-2-2018_EDITED_v2_map.py

🐛 boyd test config has an inverted check on hidden families

---

kf_lib_data_ingest/etl/transform/transform.py

Null of a given attribute will always map to the same thing. Don't
flood the log with output for every single one.

🔇 Don't emit so much null conversion spam

---

kf_lib_data_ingest/common/concept_schema.py
kf_lib_data_ingest/common/stage.py
kf_lib_data_ingest/common/type_safety.py
kf_lib_data_ingest/etl/configuration/dataset_ingest_config.py
kf_lib_data_ingest/etl/extract/extract.py
kf_lib_data_ingest/etl/ingest_pipeline.py
requirements.txt
tests/data/test_study/dataset_ingest_config.yml
tests/test_extract_stage.py
tests/test_ingest_stage.py
tests/test_transform_stage.py

<strike>Currently outputs something like...
```
POST-EXTRACT ACCOUNTING
Participants  -  'CONCEPT|PARTICIPANT|ID'
-----------------------------------------
Found: 24
Expected: 24 ✅
Specimens  -  'CONCEPT|BIOSPECIMEN|ID'
--------------------------------------
Found: 60
Expected: 'expected_num_specimens' not set in /path/to/study/dataset_ingest_config.yml
Genomic Files  -  'CONCEPT|GENOMIC_FILE|FILE_PATH'
--------------------------------------------------
Found: 180
Every CONCEPT|BIOSPECIMEN|ALIQUOT_ID should (definitely) have a CONCEPT|PARTICIPANT|ID...
✅
Every CONCEPT|BIOSPECIMEN|ID should (definitely) have a CONCEPT|PARTICIPANT|ID...
❌...but these don't:
{ what doesn't : where it is }
{4: {'study_data/simple_headered_tsv_2.tsv',
'study_data/unsimple_xlsx_1.xlsx'},
5: …
```

✨ Post-extract accounting

---

kf_lib_data_ingest/common/misc.py

Gen3 throws internal errors if you ask it to walk and chew gum at the same time. 
Then the dataservice forwards the 500 status, which basically kills GF endpoint access until https://github.com/kids-first/kf-api-dataservice/issues/487 gets fixed.

🐛 The dataservice throws 500 if gen3 does

---

kf_lib_data_ingest/cli.py
kf_lib_data_ingest/etl/ingest_pipeline.py
tests/conftest.py
tests/test_logging.py

The pipeline wasn't really made to be reusable, but it's sometimes
treated like it is, and that seems dangerous. This migrates pieces of the
pipeline so that configuration arguments all go to init, the logger
gets set up right away, and the stages get constructed directly instead
of being put into (and then pulled back out of) bags of parameters.
It resists treating DataIngestPipeline instances as things to modify and
run again and gets us closer to having a "do my stuff" executive
invocation.
This is part one of converting the DataIngestPipeline class into a
straightforward ingest_data function since you basically just call
run right away _anyway_.
This also adds some kwargs which override the defaults set in the dataset_ingest_config.yaml, but that's mostly just to work in the current …

♻️ reshape the stage queue

---

kf_lib_data_ingest/common/misc.py

Retrying a request is basically free. If the service is going to come back up (which at least in our case we know it will), I think we should give it more time.
fixes #204

🐛 Retrying is free. Don't give up so easily.

---

kf_lib_data_ingest/cli.py
kf_lib_data_ingest/common/misc.py
kf_lib_data_ingest/common/stage.py
kf_lib_data_ingest/etl/extract/extract.py
kf_lib_data_ingest/etl/ingest_pipeline.py
kf_lib_data_ingest/etl/load/load.py
kf_lib_data_ingest/etl/stage_analyses.py
kf_lib_data_ingest/etl/transform/transform.py
requirements.txt
tests/test_extract_stage.py
tests/test_ingest_pipeline.py
tests/test_ingest_stage.py
tests/test_transform_stage.py

We can separate tallying from actual analysis and then do the analysis in a more controlled and comparable way.
Make a uniform stage tally format that each stage is repsonsible for building, and then we can give that to whatever tests we want.

♻️ Separate stage tally format from checks

---

kf_lib_data_ingest/etl/transform/guided.py
kf_lib_data_ingest/etl/transform/transform.py
tests/test_guided_transform.py
tests/test_transform_stage.py

Fix unique key generation 
- Only build unique key strings if all required cols are present and the values are not null. 
- For optional cols that are null, use a value of Not Reported in the unique key string
Fix standard to target instance building
- Don't build target instances with a null id

🐛 Fix rogue nulls

---

kf_lib_data_ingest/etl/configuration/target_api_config.py
kf_lib_data_ingest/etl/transform/guided.py
kf_lib_data_ingest/etl/transform/standard_model/model.py
kf_lib_data_ingest/etl/transform/transform.py
tests/test_guided_transform.py
tests/test_null_processing.py
tests/test_standard_model.py

kids_first.py was calling it target_concepts
target_api_config.py class was calling concept_schemas
Make them both target_concepts

♻️ Make target api file fields, class var names consistent

---

kf_lib_data_ingest/etl/configuration/base_config.py
tests/test_configs.py

I don't think we should need to manually forward everything we want to use from a config file.
See e.g.
`self.target_concepts = self.contents.target_concepts` in TargetAPIConfig.__init__

✨ Remove need to manually forward config elements

---

kf_lib_data_ingest/factory/templates/my_study/data/clinical.tsv
kf_lib_data_ingest/factory/templates/my_study/dataset_ingest_config.yml
kf_lib_data_ingest/factory/templates/my_study/extract_configs/extract_config.py
kf_lib_data_ingest/factory/templates/my_study/transform_module.py
tests/test_create_new_ingest.py

In preparation for #188 
Update the template ingest package so that it will successfully run through the ingest pipeline after its generated via `kidsfirst new` command
Added 1 source data file, 1 working extract config, a working transform module, and expected counts

♻️ Make template ingest pkg usable

---

kf_lib_data_ingest/common/concept_schema.py
kf_lib_data_ingest/etl/transform/transform.py
tests/test_transform_stage.py

- Fix typo in phenotype unique key composition
- Fix unique key generation 
For a unique key with optional cols, if the col is missing or the col is present but the value is missing, fill in with Not Reported

🐛 Fix bug with optional components in unique keys

---

scripts/entrypoint.sh

**Problem**
Docker container runs as root user or a user different than Jenkins user. When we run the container in the kf-ingest-packages CI pipeline on Jenkins host, we need to bind mount the kf-ingest-packages/kf_ingest_packages/packages directory into the container. When container is running ingest it writes logs/outputs as root into that bind mounted directory. When Jenkins tries to do its usual clean up it tries to delete the kf-ingest-packages/packages directory which contains logs/outputs that are owned by root.
**Solution**
Update docker container entrypoint so that it optionally cleans up (rm -rf) the ingest package dir after ingest finishes or fails. This is controlled by the CLEANUP env var which will contain the package name to delete. This is used in the CI script for …

🐳 Docker container clean up after ingest ends

---

scripts/entrypoint.sh

Remove the code inside the Docker entrypoint that optionally deletes the ingest package after running ingest. 
This was needed before because during a [kf-ingest-packages](https://github.com/kids-first/kf-ingest-packages) CI scenario the Docker container needed to delete any files it produced on the host system since those files are written as root and cannot be deleted by the Jenkins user.
Not needed any more because the Docker container no longer writes files to the host system. See https://github.com/kids-first/kf-ingest-packages/pull/24

🔥 Rm docker self clean from entrypoint

---

kf_lib_data_ingest/common/misc.py
kf_lib_data_ingest/etl/configuration/log.py

Move timestamp function into a shared space instead of in log configuration, and create default format variables in case someone else wants to use them with another invocation to logging

♻️ minor cleanup

---

kf_lib_data_ingest/app/cli.py

the click.Choice docstring says:
"You should only pass a list or tuple of choices. Other iterables
(like generators) may lead to surprising results."
fixes #272

🐛 click.Choice needs a list, not an iterator

---

kf_lib_data_ingest/common/misc.py
kf_lib_data_ingest/etl/configuration/log.py

The timestamp function isn't logging-specific and can (and will be) used elsewhere.
Also slightly refactors the setup_logger function using module defaults.

♻️ move timestamp() to common and refactor setup_logger

---

CHANGELOG.md

Feature Emojis: ♻️ x2 ✨ x1 🐛 x3 🚸 x1 
Feature Labels: [bug](http://api.github.com/repos/kids-first/kf-lib-data-ingest/labels/bug) x3 [feature](http://api.github.com/repos/kids-first/kf-lib-data-ingest/labels/feature) x1 [other](http://api.github.com/repos/kids-first/kf-lib-data-ingest/labels/other) x1 [refactor](http://api.github.com/repos/kids-first/kf-lib-data-ingest/labels/refactor) x2 
- (#285) ♻️ Update cat study - @znatty22
- (#284) ♻️ move timestamp() to common and refactor setup_logger - @fiendish
- (#283) 🚸 Nicer handling of missing(stubbed) data - @fiendish
- (#279) 🐛 Fix user defined test bugs - @znatty22
- (#274) 🐛 Clean up the transform output df - @fiendish
- (#273) 🐛 click.Choice needs a list, not an iterator - @fiendish
- (#254) ✨ Post transform accounting - @fiendish

🔖 Release 0.3.0

---

kf_lib_data_ingest/common/misc.py
kf_lib_data_ingest/etl/load/load.py
kf_lib_data_ingest/etl/transform/transform.py
tests/test_extract_stage.py
tests/test_misc.py

Will recurse into lists and dicts to clean their contents for comparison across stages and then revert to their original native type.
closes #313

🐛 Load objects instead of object-like strings

---

kf_lib_data_ingest/common/pandas_utils.py

A friendly message that describes the problem is better than a generic
KeyError from deep inside pandas.

🚸 Add friendly merge column alert

---

kf_lib_data_ingest/common/misc.py
kf_lib_data_ingest/common/pandas_utils.py
kf_lib_data_ingest/etl/extract/extract.py
requirements.txt
tests/test_logging.py
tests/test_pandas_utils.py

This lets you specify a group ID for Split objects, such that two
Splits on the same row with the same group ID will be applied
simultaneously in parallel rather than sequentially.
closes #301

✨ Add grouping of Splits

---

tests/data/simple_study/extract_configs/extract_config.py
tests/test_app_settings.py
tests/test_concept_graph.py
tests/test_configs.py
tests/test_extract_operations.py
tests/test_extract_stage.py
tests/test_file_retriever.py
tests/test_guided_transform.py
tests/test_ingest_stage.py
tests/test_logging.py
tests/test_standard_model.py
tests/test_target_api_config.py
tests/test_transform_stage.py
tests/test_type_safety.py

When using pytest.raises as a context manager, normal context manager
rules apply, and the exception raised must be the final line in the
scope of the context manager. Lines of code after that within the scope
of the context manager will not be executed.
A few valid but verbose uses were also changed for consistency.
closes #300

🐛 Fix invalid use of pytest context managers

---

kf_lib_data_ingest/app/cli.py
kf_lib_data_ingest/etl/ingest_pipeline.py
kf_lib_data_ingest/etl/load/load.py

Network traffic for loading is slow, so support aborting and resuming
later without resubmitting data that has already been submitted.
The given ID will get submitted. This is to support ID prefixes ('DG',
'FM', etc) where the expectation is to begin loading at the first one
without gratuitous checks and filtering.
closes #317

✨ Support resuming load from a given target ID or prefix

---

.gitignore

This PR updates `.gitignore` as ignoring dot files and folders. This is same as kids-first/kf-ingest-packages#57.

👷 Blanket ignore all dotfiles

---

kf_lib_data_ingest/app/cli.py
kf_lib_data_ingest/etl/configuration/log.py
kf_lib_data_ingest/etl/load/load.py

All entities within a group are thrown into a background worker pool unless the resume target hasn't been found yet.
This does not cross entity type group boundaries. That would require
significant enough extra complexity to ensure proper foreign key load
ordering that I don't think the minimal extra gain would be worth it.
Changes in cli.py are just to add the existing keywords to `kidsfirst test` as well.
closes #34

✨ Optional multithreaded loading

---

kf_lib_data_ingest/target_apis/kids_first.py

ETag -> etag, SHA-1 -> sha1, etc
closes #361

🐛 Indexd mandates a specific hash key format

---

kf_lib_data_ingest/etl/ingest_pipeline.py

Skipping a stage signals that its counts are either valid or irrelevant. So skip validating counts in output read from disk.

♻️⚡️ Don't validate counts from prior run

---

kf_lib_data_ingest/common/file_retriever.py
kf_lib_data_ingest/common/misc.py
kf_lib_data_ingest/etl/extract/extract.py
tests/test_file_retriever.py

If FileRetriever is initialized without an auth_configs argument, it now
looks to see if someone set a static one. This lets extract config
modules use the auth_configs structure, which is an application level
setting.
closes #373

✨ FileRetriever static auth configs

---

kf_lib_data_ingest/etl/load/load.py

Catch a special case where an existing entity relationship has a
different external ID than what we want it to have.
closes #386

🐛 Update external_id mismatch on existing link

---

kf_lib_data_ingest/etl/load/load.py

Make sure that an existing entity relationship (e.g. a BSDG) gets updated with the external ID that we want.
closes #386

🐛 Update entity relationship external_id on mismatch

---

kf_lib_data_ingest/etl/stage_analyses.py

closes #392 
Consider that this would otherwise show all 15654 lines in the table because just 2 are missing:
```
ExtractStage
============
UNIQUE COUNTS:
{'GENOMIC_FILE|FILE_NAME': 15654}
⚠️ No expected counts registered.
TransformStage
==============
UNIQUE COUNTS:
{'GENOMIC_FILE|FILE_NAME': 15652}
⚠️ No expected counts registered.
COMPARING COUNTS
================
❌ Column values for GENOMIC_FILE|FILE_NAME not equal between ExtractStage and TransformStage
Number of different values = 2
+--------------------------------------------------------------------------+---------------------+
| In ExtractStage                                                          | In TransformStage   |
|--------------------------------------------------------------------------+---------------------|
| …
```

🔇 Only show comparison mismatches

---

kf_lib_data_ingest/network/oauth2.py
kf_lib_data_ingest/network/utils.py
tests/test_file_retriever.py

Add a test to stop a future change to FileRetriever from breaking functionality that
allows to call FileRetriever().get() as input to a read function even
though the temporary downloads go away when the FR leaves scope.

✅ Keep FileRetriever().get() safe

---

kf_lib_data_ingest/etl/extract/extract.py
kf_lib_data_ingest/etl/transform/guided.py
kf_lib_data_ingest/etl/transform/transform.py
templates/my_study/tests/test_custom_counts.py

Closes #342, Part of https://github.com/d3b-center/clinical-data-flow/issues/22
**Tested by doing a dry-run of Chung's ingest package**
```
2020-02-11 08:12:23,220 - LoadStage - Thread: MainThread - INFO - END LoadStage. Time elapsed: Sec: 35.35092210769653 Min: 0.0 Hours: 0.0
```
**The count failures for genomic files are expected.**
```
======================
COUNT ANALYSIS RESULTS
======================
❌ Count Analysis Failed!
Ingest package: /Users/singhn4/Projects/kids_first/kf-ingest-packages/kf_ingest_packages/packages/SD_46SK55A3/ingest_package_config.py
Completed at: 2020-02-11T08:12:33.285719+11:00
ExtractStage
============
UNIQUE COUNTS:
{'BIOSPECIMEN_GROUP|ID': 2338,
'BIOSPECIMEN|ANALYTE': 1,
'BIOSPECIMEN|ANATOMY_SITE': 6,
'BIOSPECIMEN|COMPOSITION': 15,
'BIOSPECIMEN|ID': …
```

⚡️🚧 Only do accounting on concept instances 

---

kf_lib_data_ingest/common/stage.py
kf_lib_data_ingest/etl/extract/extract.py
kf_lib_data_ingest/etl/ingest_pipeline.py
kf_lib_data_ingest/etl/transform/guided.py
kf_lib_data_ingest/etl/transform/transform.py
tests/test_extract_stage.py
tests/test_transform_stage.py

This also removes source files from the Extract output, which I've been
meaning to do for a while. Extract configs can load arbitrary data from
anywhere at any time, not just the designated variable, so it's
misleading to indicate otherwise.

♻️ Deduplicate discovery

---

kf_lib_data_ingest/app/settings/base.py
kf_lib_data_ingest/app/settings/development.py
kf_lib_data_ingest/app/settings/production.py

The study creator is moving away from oath2.
closes #461
part of d3b-center/clinical-data-flow#102

👽 Use token auth for prod study creator

---

requirements.txt

> black 20.8b1 requires click>=7.1.2, but you'll have click 7.0 which is incompatible.

⬆️ Upgrade click dependency

---

kf_lib_data_ingest/common/constants.py

This PR adds 9 sequencing centers to `constants.py`. This closes #483.

✨ Add sequencing centers

---

kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py

making a pr to get the ball rolling on the issue i found with booleans. 
When ingesting an ingest package, I found the setting `CONCEPT.GENOMIC_FILE.VISIBLE` to `constants.COMMON.FALSE` created the correct output in `sent_messages.json` but when inspecting in dataservice, visible was set to false.
Commenting out the 'boolean': bool line fixed this.

🐛 comment out bool json type cast

---

kf_lib_data_ingest/common/io.py

Modify `file_to_path_list` function so that the file paths include the root. Closes #506.

🐛 Fix path_to_file_list

---

kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py

🐛 Family ID is optional for Participants

---

.gitignore
kf_lib_data_ingest/common/stage.py
kf_lib_data_ingest/etl/ingest_pipeline.py
kf_lib_data_ingest/validation/reporting/base.py
kf_lib_data_ingest/validation/reporting/markdown.py
kf_lib_data_ingest/validation/reporting/sample_validation_results.py
kf_lib_data_ingest/validation/reporting/table.py
kf_lib_data_ingest/validation/validation.py
tests/test_validation.py

Closes #480 
Currently outputs two types of validation reports: TSV and markdown. 
**TSV**
This isn't really a report, but 3 tables: `type_counts.tsv`,`files_validated.tsv`, `validation_results.tsv`. The `validation_results.tsv` table is a less nested, less verbose version of the original validation results coming from the graph validator. 
I added this because we were told the analysts want a tabular version of the validation results, but I think new markdown report will satisfy their needs. So we can get rid of this if we don't think its useful
**Markdown**
The markdown report is meant to be a more human friendly/readable form of the original validation results from the graph validator. The report currently looks like this:
**/Users/singhn4/Projects/pull-request-reviews/kf-lib-data-inges …

✨ Validation Reports

---

kf_lib_data_ingest/common/constants.py

adds consent group for health/medical/biomedical for not-for-profit organizations only.Information for this consent group can be found [here](https://osp.od.nih.gov/wp-content/uploads/standard_data_use_limitations.pdf). found in one of the cohorts of `SD_Z6MWD3H0`

✨add hmb-npu to constants.CONSENT_TYPE

---

kf_lib_data_ingest/etl/load/load_v1.py
kf_lib_data_ingest/etl/load/load_v2.py
tests/test_load_stage.py

Needed for dry-loading relationship entities, because otherwise their
primary components can't be built.
closes #530

🐛 Fake-cache target IDs in dry run mode 

---

kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py

We have two formats for family relationship. We often get PID+relationship_to_proband, but we need P1+P2+relationship.

✨ Convert family relations to P1+P2+rel

---

kf_lib_data_ingest/common/constants.py

See https://github.com/kids-first/kf-api-dataservice/pull/559

💬 New constant for marrow aspiration

---

kf_lib_data_ingest/app/cli.py
kf_lib_data_ingest/etl/ingest_pipeline.py
kf_lib_data_ingest/etl/load/load_v2.py

Using kidsfirst `test`/`ingest --dry-run` (or loading into a local private dataservice), you can add `--clear_cache --query_url=https://kf-api-dataservice.kidsfirstdrc.org` to query against the actual prod dataservice to find matching production kfids to see in the logs exactly what will get added vs updated.
@chris-s-friedman asked for this and I thought it was a good idea

✨ Add option to query from another source in Load

---

kf_lib_data_ingest/common/constants.py

adds maf file format. According to @bmennis, maf files are from consensus calling. The appropriate data type for maf files is `constants.GENOMIC_FILE.DATA_TYPE.ANNOTATED_SOMATIC_MUTATIONS`

💬 Add maf format to constants

---

kf_lib_data_ingest/network/utils.py
kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py

This chooses to null ones that are too big instead of assigning the wrong value.

🐛 Ensure integers fit into allocated bits

---

kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py

It's probably a bad idea to silently wedge values into other slots even if in theory they should be 1:1. 
This will force the operator to assign CONCEPT.SEQUENCING.ID.

♻️ Don't silently cross-assign SE.SL/SE.ID

---

kf_lib_data_ingest/etl/load/load_v1.py
kf_lib_data_ingest/etl/load/load_v2.py
kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py

Tested locally
Closes #545 
Closes #569

🔊 🐛 More verbose loader logging + loader fixes

---

kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py
tests/data/kfid_study/data/clinical.tsv
tests/data/kfid_study/extract_configs/extract_config.py
tests/data/kfid_study/ingest_package_config.py
tests/data/kfid_study/transform_module.py
tests/test_kidsfirst_api_plugin.py

If the record is missing requisite key fields for the two related
sub-entities in a relation entity (BSGF, etc), just skip populating the
external_id field instead of raising an exception.

🐛 Don't error on relation external_id without key fields

---

kf_lib_data_ingest/common/concept_schema.py
kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py

the kids first api has consent type and dbgap consent code as attributes of biospecimen. although these values are assigned elsewhere (see https://github.com/kids-first/kf-update-dbgap-consent) for non-dbgap studies or for studies where dbgap has not released the data, these values can only be set in standalone scripts. adding these two items to the biospecimen concept allows these to be added during ingest.

✨ Add consent_type and dbgap_consent_code to BS

---

kf_lib_data_ingest/common/misc.py

Resolve OverflowError so etag is not interpreted as inf

🐛 Change ValueError to Exception

---

kf_lib_data_ingest/common/constants.py
kf_lib_data_ingest/etl/configuration/base_config.py

This PR adds `'Drosophila melanogaster'` (fruit fly) and `'Mus musculus'` (house mouse) to the species enum according to kids-first/kf-api-dataservice#572.

✨ Add Fly and 🐭 

---

kf_lib_data_ingest/etl/load/load_v1.py
tests/test_kidsfirst_api_plugin.py

Adds a new log message at the end that looks like
```
2021-05-09 22:43:44,002 - LoadStage - Thread: MainThread - INFO - Load Summary:
{'biospecimen': {'ADD': 0, 'UPDATE': 5},
'biospecimen_genomic_file': {'ADD': 10, 'UPDATE': 0},
'genomic_file': {'ADD': 0, 'UPDATE': 10},
'sequencing_experiment': {'ADD': 0, 'UPDATE': 5},
'sequencing_experiment_genomic_file': {'ADD': 10, 'UPDATE': 0}}
```
etc
Using dry run with a --query_url set will give a summary report for the number of new vs existing entities.

🔊 Rearrange target ID inquiry to improve load logging

---

kf_lib_data_ingest/common/constants.py

To make hash names consistent with what's in the kidsfirst dataservice, make hash names all lower case and without special characters. 
This also means that we no longer have to force etag to be lower case, as in the [template s3_scrape extract config](https://github.com/kids-first/kf-api-study-creator/blob/master/creator/extract_configs/templates/s3_scrape_config.py#L138). 
This also makes values for md5 and sha256 match what's already registered for those values in the hash array, e.g. [GF_N0CKF2WA](https://kf-api-dataservice.kidsfirstdrc.org/genomic-files/GF_N0CKF2WA): 
```json
{
"hashes": {
"etag": "e0658c69f26d6540ac111ef055cec933-8077",
"md5": "3a344aa5e436aee9ddb67e329384b103",
"sha256": "cba6338f8fc267e86585f7d10a88faaac7b5921a906f805a9be2408a327aa497"
}
}
```

✏️ Make hash names lower case & no special characters

---

kf_lib_data_ingest/etl/load/load_base.py

🐛 Assign IDs to new entities in dry_run mode that can be re-used during the run

---

kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py

Partially addresses #629.
Raise a `RequestException` in the Kids First target API plugin when the response has a status code of 200 or 201 but is not in the form that is expected.

🐛 Raise in KF target when response is bad with good status

---

kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py

add ability to specify external ids for diagnos, phenotype, and outcome. this is to enable the use of external ID when needed.

:sparkles: specify external IDs for clinical markers

---

kf_lib_data_ingest/common/constants.py

add snRNAseq as valid experiment strategy value, and update Single Cell RNA-Seq to match structure of other values: scRNAseq
note: there are 30 existing sequencing experiment rows that have "Single Cell RNA-Seq" as the experiment strategy value. We have been notified that these should have been registered as snRNAseq (single nucleus) not single cell. I am patching those today so they will have the value snRNAseq. So, even though I am updating the structure of the Single Cell RNA-Seq value to be scRNAseq in kf utils and the data service, I will not be creating any cases of conflict where the existing data values in the kf db are mis-aligned with the constraints in the API.
This PR also adds the value snRNAseq to ensure that the new value for the "fixed" sequencing experiment rows is a …

:sparkles: add snRNAseq experiment strategy

---

kf_lib_data_ingest/common/concept_schema.py
kf_lib_data_ingest/common/constants.py
kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py

Add visibility reason and comment, enumerated values for visibility reason, and adds both concepts to the kids first target api config.
See https://github.com/kids-first/kf-api-dataservice/pull/604 for the addition of these values into the kidsfirst dataservice

✨ create concepts for visibility reason and comment

---

kf_lib_data_ingest/common/constants.py

For long reads sequencing, the `se.library_selection` field should be set to either CCS or CLR.
- circular consensus sequencing (CCS)
- continuous long reads (CLR)
These values should be added as constants in the ingest library so that they will be accepted during long reads ingest. cc: @HigginsD3b

:heavy_plus_sign: add new constants for LRs

---

docs/source/design/concepts/index.rst
docs/source/design/concepts/samples_and_specimens.rst
docs/source/design/overview.rst
kf_lib_data_ingest/common/concept_schema.py
kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py

This PR adds the concept for Sample. The approach for adding sample is to give it many of the same entities of biospecimen that make sense, such as shipping information, volume, etc and then make sample a parent to biospecimen, to indicate the relationship between biospecimen and sample. In the kf target api config, biospecimen and sample may be used interchangeable with preference given towards the sample entry.
Documentation for concepts is also added to the documentation site.

✨ Add Sample Concept

---

kf_lib_data_ingest/target_api_plugins/kids_first_dataservice.py

workflow_tool and workflow_type are misspelled
See [D3B-723](https://d3b.atlassian.net/browse/D3B-723)
[D3B-723]: https://d3b.atlassian.net/browse/D3B-723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

🚑️ Fix typo in kf target_api_plugin

---

kf_lib_data_ingest/common/constants.py

Add the `Upenn` as sequencing center
`{"_links":{"biospecimens":"/biospecimens?sequencing_center_id=SC_K20D8V6F","collection":"/sequencing-centers","self":"/sequencing-centers/SC_K20D8V6F","sequencing_experiments":"/sequencing-experiments?sequencing_center_id=SC_K20D8V6F"},"_status":{"code":201,"message":"sequencing_center SC_K20D8V6F created"},"results":{"created_at":"2024-11-07T14:23:09.092805+00:00","external_id":null,"kf_id":"SC_K20D8V6F","modified_at":"2024-11-07T14:23:09.092814+00:00","name":"University of Penn","visibility_comment":null,"visibility_reason":null,"visible":true}}`

:necktie: add upenn
